# Generated by Django 4.2.1 on 2024-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_loadmodel_load_alter_repsmodel_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadmodel',
            name='load',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='repsmodel',
            name='reps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='setsmodel',
            name='sets',
            field=models.IntegerField(blank=True),
        ),
    ]
