# Generated by Django 4.2.1 on 2024-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
